# Check https://docs.docker.com/reference/compose-file for the configuration reference
services:
  host-1:
    image: ghcr.io/netmgmt/gp3:latest
    container_name: host-1
    hostname: host-1
    volumes:
      - ./deliverables/host1:/home/kenobi/.deliverables
    networks:
      lab-net:
        ipv4_address: 10.0.123.2

  host-2:
    image: ghcr.io/netmgmt/gp3:latest
    container_name: host-2
    hostname: host-2
    volumes:
      - ./deliverables/host2:/home/kenobi/.deliverables
    networks:
      lab-net:
        ipv4_address: 10.0.123.3

  host-3:
    image: ghcr.io/netmgmt/gp3:latest
    container_name: host-3
    hostname: host-3
    volumes:
      - ./deliverables/host3:/home/kenobi/.deliverables
    networks:
      lab-net:
        ipv4_address: 10.0.123.4

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.123.0/24
