###############################################################################
authCommunity log,execute,net public

# Generic traps
traphandle SNMPv2-MIB::coldStart             /home/kenobi/bin/trapProcessor.sh cold
traphandle SNMPv2-MIB::warmStart             /home/kenobi/bin/trapProcessor.sh warm
traphandle IF-MIB::linkDown                  /home/kenobi/bin/trapProcessor.sh down
traphandle IF-MIB::linkUp                    /home/kenobi/bin/trapProcessor.sh up
traphandle SNMPv2-MIB::authenticationFailure /home/kenobi/bin/trapProcessor.sh auth

# This one is deprecated...
traphandle .1.3.6.1.6.3.1.1.5.6              /home/kenobi/bin/trapProcessor.sh egp-neighbor-loss

# Enterprise-specific traps
traphandle UAH-AUT-GR-EXAMPLES-TRAP-MIB::uahAutGrTrapBasic            /home/kenobi/bin/trapProcessor.sh uah.aut.gr.traps.trapBasic
traphandle UAH-AUT-GR-EXAMPLES-NOTIFICATION-MIB::uahAutGrNotifEvBasic /home/kenobi/bin/trapProcessor.sh uah.aut.gr.notifications.eventBasic
