# Check https://docs.docker.com/reference/compose-file for the configuration reference
services:
  agent:
    image: ghcr.io/netmgmt/gp1:latest
    container_name: agent
    hostname: agent
    networks:
      lab-net:
        ipv4_address: 10.0.123.2

  manager:
    image: ghcr.io/netmgmt/gp1:latest
    container_name: manager
    hostname: manager
    networks:
      lab-net:
        ipv4_address: 10.0.123.3

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.123.0/24
