# Sample SNMPv3 setup: be sure to check the docs!
agentAddress udp:161,udp6:[::1]:161

# SNMPv3 user
createUser vagrant SHA vagrant1234 AES vagrant1234
rouser vagrant priv

sysLocation    Docker Lab GP4
sysContact     alumno@uah.es
