# Default SNMP client configuration. This file should be located on
# /home/kenobi/.snmp/snmp.conf. Be sure to read [0] for more info.
# 0: http://net-snmp.sourceforge.net/docs/man/snmp.conf.html

# TODO: Fill in all the configuration values!
defVersion
defSecurityName
defSecurityLevel
defAuthType
defAuthPassphrase
defPrivType
defPrivPassphrase
