# Sample SNMPv3 setup: be sure to check the docs!
agentAddress udp:161,udp6:[::1]:161

# SNMPv3 user
createUser kenobi SHA kenobi1234 AES kenobi1234
rouser kenobi priv

sysLocation    Docker Lab GP4
sysContact     alumno@uah.es
